### ISSUE TITLE
Milestone 1 checklist

### ISSUE THREAD

**Issue by smwatts** [UBC-MDS/mdsSurvey#2]
- [x] Identify the question that your team in interested in answering with the survey
- [x] Identify the other questions you plan to ask in your survey to identify confounding variables and justify/explain why you plan to include them
- [x] Describe how you plan to analyze the survey results (e.g., what statistical test(s) do you plan to employ?)
- [x] Discuss the aspects of the [UBC Office of Research Ethics document](
https://ethics.research.ubc.ca/sites/ore.ubc.ca/files/documents/Online_Survey-GN.pdf) on Using Online Surveys that are relevant to your proposed survey
